
**** Log file opened at 2025-08-01 14:39:55.602126 UTC-04:00 (Hora verano Sudamérica Pacífico), Encoding UTF-8
NW RFC Library: SDK variant, Release 750 Patch Level 14
Compilation date          : Jun 15 2024 06:07:33
CPIC library              : 754.2024.02.29 version 3
NI library                : 40
Kernel Release            : 754 Patch Level 325
Current working directory : C:\Proyectos Desarrollo-Invertec\Invertec-Python\rfc_sap
Program                   : python
Process ID                : 19704
User                      : wcorrea
Hardware                  : PC with Windows NT 12x AMD64 Level 6 (Mod 154 Step 4)
Binary Type               : 64bit
Operating_system          : Windows NT 10.0
Hostname                  : WCORREA
IP address                : 192.168.2.69
IPv6 address              : fe80::ffb4:c3ab:ffc8:8b05
Global trace level        : 0

2025-08-01 14:39:55.603219 [04796] >> Info entry
	Did not find config file C:\Proyectos Desarrollo-Invertec\Invertec-Python\rfc_sap\sapnwrfc.ini.

**** Log file opened at 2025-08-04 09:10:38.587481 UTC-04:00 (Hora verano Sudamérica Pacífico), Encoding UTF-8
NW RFC Library: SDK variant, Release 750 Patch Level 14
Compilation date          : Jun 15 2024 06:07:33
CPIC library              : 754.2024.02.29 version 3
NI library                : 40
Kernel Release            : 754 Patch Level 325
Current working directory : C:\Proyectos Desarrollo-Invertec\Invertec-Python\rfc_sap
Program                   : python
Process ID                : 04656
User                      : wcorrea
Hardware                  : PC with Windows NT 12x AMD64 Level 6 (Mod 154 Step 4)
Binary Type               : 64bit
Operating_system          : Windows NT 10.0
Hostname                  : WCORREA
IP address                : 192.168.2.77
IPv6 address              : fe80::ffb4:c3ab:ffc8:8b05
Global trace level        : 0

2025-08-04 09:10:38.585915 [06416] >> Info entry
	throwRfcErrorMsg called at:
	0x7FFAB89693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFAB89693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFAB89693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFAB89693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFAB89693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFAB89693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFAB892C1E0: sapnwrfc.dll!RfcInvoke()
	0x7FFAB892C1E0: _cyrfc.cp38-win_amd64.pyd!RfcInvoke()
	0x7FFAB892C1E0: _cyrfc.cp38-win_amd64.pyd!RfcInvoke()
	0x7FFAB948E4A4: python38.dll!Py_FatalError()
	0x7FFAB9388BE0: python38.dll!Py_CheckFunctionResult()
	0x7FFAB938A980: python38.dll!PyEval_EvalFrameDefault()
	0x7FFAB93867C0: python38.dll!PyEval_EvalCodeWithName()
	0x7FFAB939B6A4: python38.dll!PyEval_EvalCodeEx()
	0x7FFAB939B670: python38.dll!PyEval_EvalCode()
	0x7FFAB9399E74: python38.dll!PyArena_New()
	0x7FFAB9399E74: python38.dll!PyArena_New()
	0x7FFAB946A18C: python38.dll!PyRun_FileExFlags()
	0x7FFAB9469608: python38.dll!PyRun_SimpleFileExFlags()
	0x7FFAB9530D84: python38.dll!PyRun_AnyFileExFlags()
	0x7FFAB948E4A4: python38.dll!Py_FatalError()
	0x7FFAB93F6524: python38.dll!Py_RunMain()
	0x7FFAB93F6524: python38.dll!Py_RunMain()
	0x7FFAB93F61E4: python38.dll!Py_Main()
	0x7FFAB93F61E4: python.exe!Py_Main()
	0x7FFB97A2E8C0: KERNEL32.DLL!BaseThreadInitThunk()
	0x7FFB99ABC320: ntdll.dll!RtlUserThreadStart()


**** Log file opened at 2025-08-04 10:02:46.161760 UTC-04:00 (Hora verano Sudamérica Pacífico), Encoding UTF-8
NW RFC Library: SDK variant, Release 750 Patch Level 14
Compilation date          : Jun 15 2024 06:07:33
CPIC library              : 754.2024.02.29 version 3
NI library                : 40
Kernel Release            : 754 Patch Level 325
Current working directory : C:\Proyectos Desarrollo-Invertec\Invertec-Python\rfc_sap
Program                   : python
Process ID                : 24860
User                      : wcorrea
Hardware                  : PC with Windows NT 12x AMD64 Level 6 (Mod 154 Step 4)
Binary Type               : 64bit
Operating_system          : Windows NT 10.0
Hostname                  : WCORREA
IP address                : 192.168.2.77
IPv6 address              : fe80::ffb4:c3ab:ffc8:8b05
Global trace level        : 0

2025-08-04 10:02:46.156202 [16216] >> Info entry
	throwRfcErrorMsg called at:
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB2C1E0: sapnwrfc.dll!RfcInvoke()
	0x7FFADCB2C1E0: _cyrfc.cp38-win_amd64.pyd!RfcInvoke()
	0x7FFADCB2C1E0: _cyrfc.cp38-win_amd64.pyd!RfcInvoke()
	0x7FFADDFAE4A4: python38.dll!Py_FatalError()
	0x7FFADDEA8BE0: python38.dll!Py_CheckFunctionResult()
	0x7FFADDEAA980: python38.dll!PyEval_EvalFrameDefault()
	0x7FFADDEA8BE0: python38.dll!Py_CheckFunctionResult()
	0x7FFADDEAA980: python38.dll!PyEval_EvalFrameDefault()
	0x7FFADDEA8BE0: python38.dll!Py_CheckFunctionResult()
	0x7FFADDEAA980: python38.dll!PyEval_EvalFrameDefault()
	0x7FFADDEA67C0: python38.dll!PyEval_EvalCodeWithName()
	0x7FFADDEBB6A4: python38.dll!PyEval_EvalCodeEx()
	0x7FFADDEBB670: python38.dll!PyEval_EvalCode()
	0x7FFADDEB9E74: python38.dll!PyArena_New()
	0x7FFADDEB9E74: python38.dll!PyArena_New()
	0x7FFADDF8A18C: python38.dll!PyRun_FileExFlags()
	0x7FFADDF89608: python38.dll!PyRun_SimpleFileExFlags()
	0x7FFADE050D84: python38.dll!PyRun_AnyFileExFlags()
	0x7FFADDFAE4A4: python38.dll!Py_FatalError()
	0x7FFADDF16524: python38.dll!Py_RunMain()
	0x7FFADDF16524: python38.dll!Py_RunMain()
	0x7FFADDF161E4: python38.dll!Py_Main()
	0x7FFADDF161E4: python.exe!Py_Main()
	0x7FFB97A2E8C0: KERNEL32.DLL!BaseThreadInitThunk()
	0x7FFB99ABC320: ntdll.dll!RtlUserThreadStart()


**** Log file opened at 2025-08-04 10:06:17.902197 UTC-04:00 (Hora verano Sudamérica Pacífico), Encoding UTF-8
NW RFC Library: SDK variant, Release 750 Patch Level 14
Compilation date          : Jun 15 2024 06:07:33
CPIC library              : 754.2024.02.29 version 3
NI library                : 40
Kernel Release            : 754 Patch Level 325
Current working directory : C:\Proyectos Desarrollo-Invertec\Invertec-Python\rfc_sap
Program                   : python
Process ID                : 21512
User                      : wcorrea
Hardware                  : PC with Windows NT 12x AMD64 Level 6 (Mod 154 Step 4)
Binary Type               : 64bit
Operating_system          : Windows NT 10.0
Hostname                  : WCORREA
IP address                : 192.168.2.77
IPv6 address              : fe80::ffb4:c3ab:ffc8:8b05
Global trace level        : 0

2025-08-04 10:06:17.901077 [17500] >> Info entry
	throwRfcErrorMsg called at:
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB693D0: sapnwrfc.dll!RfcSetAbapObjectByIndex()
	0x7FFADCB2C1E0: sapnwrfc.dll!RfcInvoke()
	0x7FFADCB2C1E0: _cyrfc.cp38-win_amd64.pyd!RfcInvoke()
	0x7FFADCB2C1E0: _cyrfc.cp38-win_amd64.pyd!RfcInvoke()
	0x7FFADDFAE4A4: python38.dll!Py_FatalError()
	0x7FFADDEA8BE0: python38.dll!Py_CheckFunctionResult()
	0x7FFADDEAA980: python38.dll!PyEval_EvalFrameDefault()
	0x7FFADDEA8BE0: python38.dll!Py_CheckFunctionResult()
	0x7FFADDEAA980: python38.dll!PyEval_EvalFrameDefault()
	0x7FFADDEA8BE0: python38.dll!Py_CheckFunctionResult()
	0x7FFADDEAA980: python38.dll!PyEval_EvalFrameDefault()
	0x7FFADDEA67C0: python38.dll!PyEval_EvalCodeWithName()
	0x7FFADDEBB6A4: python38.dll!PyEval_EvalCodeEx()
	0x7FFADDEBB670: python38.dll!PyEval_EvalCode()
	0x7FFADDEB9E74: python38.dll!PyArena_New()
	0x7FFADDEB9E74: python38.dll!PyArena_New()
	0x7FFADDF8A18C: python38.dll!PyRun_FileExFlags()
	0x7FFADDF89608: python38.dll!PyRun_SimpleFileExFlags()
	0x7FFADE050D84: python38.dll!PyRun_AnyFileExFlags()
	0x7FFADDFAE4A4: python38.dll!Py_FatalError()
	0x7FFADDF16524: python38.dll!Py_RunMain()
	0x7FFADDF16524: python38.dll!Py_RunMain()
	0x7FFADDF161E4: python38.dll!Py_Main()
	0x7FFADDF161E4: python.exe!Py_Main()
	0x7FFB97A2E8C0: KERNEL32.DLL!BaseThreadInitThunk()
	0x7FFB99ABC320: ntdll.dll!RtlUserThreadStart()


**** Log file opened at 2025-08-05 20:09:27.011025 UTC-04:00 (Hora verano Sudamérica Pacífico), Encoding UTF-8
NW RFC Library: SDK variant, Release 750 Patch Level 14
Compilation date          : Jun 15 2024 06:07:33
CPIC library              : 754.2024.02.29 version 3
NI library                : 40
Kernel Release            : 754 Patch Level 325
Current working directory : C:\Proyectos Desarrollo-Invertec\Invertec-Python\rfc_sap
Program                   : python
Process ID                : 23728
User                      : wcorrea
Hardware                  : PC with Windows NT 12x AMD64 Level 6 (Mod 154 Step 4)
Binary Type               : 64bit
Operating_system          : Windows NT 10.0
Hostname                  : WCORREA
IP address                : 192.168.1.152
IPv6 address              : fe80::ffb4:c3ab:ffc8:8b05
Global trace level        : 0

2025-08-05 20:09:27.008134 [23856] >> Error entry
	[Handle: 1212318497696	ConvID: 	Target: 	SysID: 	SysNr: 	User: 	Codepage: 4103]
	RfcCommunicationException: Return Value: 20, Code: RFC_COMMUNICATION_FAILURE, Message: 
LOCATION    CPIC (TCP/IP) on local host with Unicode
ERROR       partner '192.168.0.6:3300' not reached
TIME        Tue Aug  5 20:09:26 2025
RELEASE     754
COMPONENT   NI (network interface)
VERSION     40
RC          -10
MODULE      D:/depot/bas/754_REL/src/base/ni/nixxi.cpp
LINE        3458
DETAIL      NiPConnect2: 192.168.0.6:3300
SYSTEM CALL connect
ERRNO       10060
ERRNO TEXT  WSAETIMEDOUT: Connection timed out
COUNTER     2


**** Log file opened at 2025-08-05 20:27:52.691363 UTC-04:00 (Hora verano Sudamérica Pacífico), Encoding UTF-8
NW RFC Library: SDK variant, Release 750 Patch Level 14
Compilation date          : Jun 15 2024 06:07:33
CPIC library              : 754.2024.02.29 version 3
NI library                : 40
Kernel Release            : 754 Patch Level 325
Current working directory : C:\Proyectos Desarrollo-Invertec\Invertec-Python\rfc_sap
Program                   : python
Process ID                : 15492
User                      : wcorrea
Hardware                  : PC with Windows NT 12x AMD64 Level 6 (Mod 154 Step 4)
Binary Type               : 64bit
Operating_system          : Windows NT 10.0
Hostname                  : WCORREA
IP address                : 192.168.1.152
IPv6 address              : fe80::d465:7bf5:dd16:b61d
Global trace level        : 0

2025-08-05 20:27:52.591383 [12448] >> Error entry
	Error in receive: 20, data rec 0, status rec 0, read 0, 
LOCATION    CPIC (TCP/IP) on local host with Unicode
ERROR       connection to partner '192.168.0.6:3300' broken
TIME        Tue Aug  5 20:27:52 2025
RELEASE     754
COMPONENT   NI (network interface)
VERSION     40
RC          -6
MODULE      D:/depot/bas/754_REL/src/base/ni/nixxi.cpp
LINE        5469
DETAIL      NiIRead: P=192.168.0.6:3300; L=10.212.134.3:50093
SYSTEM CALL recv
ERRNO       10054
ERRNO TEXT  WSAECONNRESET: Connection reset by peer
COUNTER     5

2025-08-05 20:27:52.712044 [12448] >> Error entry
	[Handle: 1454827864112	ConvID: 60399867	Target: s4hanaifprd.invertec.cl	SysID: IFP	SysNr: 00	User: ETL_INVERTEC	Client: 300	Language: S	Codepage: 4103]
	RfcCommunicationException: Return Value: 20, Code: RFC_COMMUNICATION_FAILURE, Message: 
LOCATION    CPIC (TCP/IP) on local host with Unicode
ERROR       connection to partner '192.168.0.6:3300' broken
TIME        Tue Aug  5 20:27:52 2025
RELEASE     754
COMPONENT   NI (network interface)
VERSION     40
RC          -6
MODULE      D:/depot/bas/754_REL/src/base/ni/nixxi.cpp
LINE        5469
DETAIL      NiIRead: P=192.168.0.6:3300; L=10.212.134.3:50093
SYSTEM CALL recv
ERRNO       10054
ERRNO TEXT  WSAECONNRESET: Connection reset by peer
COUNTER     5

2025-08-05 20:28:13.748767 [12448] >> Error entry
	[Handle: 1454827864112	ConvID: 	Target: 	SysID: 	SysNr: 	User: 	Codepage: 4103]
	RfcCommunicationException: Return Value: 20, Code: RFC_COMMUNICATION_FAILURE, Message: 
LOCATION    CPIC (TCP/IP) on local host with Unicode
ERROR       partner '192.168.0.6:3300' not reached
TIME        Tue Aug  5 20:28:13 2025
RELEASE     754
COMPONENT   NI (network interface)
VERSION     40
RC          -10
MODULE      D:/depot/bas/754_REL/src/base/ni/nixxi.cpp
LINE        3458
DETAIL      NiPConnect2: 192.168.0.6:3300
SYSTEM CALL connect
ERRNO       10060
ERRNO TEXT  WSAETIMEDOUT: Connection timed out
COUNTER     7

